
CREATE TABLE schema_name.table_name (
	 rmpostcode varchar(8) NULL, 
  post_sector varchar(6) NULL, 
  eastings NUMERIC NULL, 
  northings NUMERIC NULL, 
  coa_code varchar(9) NULL, 
  lsoa varchar(9) NULL, 
  msoa_and_im varchar(9) NULL, 
  la_name varchar(13) NULL, 
  la_code varchar(9) NULL, 
  government_region varchar(15) NULL, 
  country varchar(8) NULL, 
  households NUMERIC NULL, 
  population NUMERIC NULL, 
  bus_sites_total NUMERIC NULL, 
  premises NUMERIC NULL, 
  exchange_name varchar(19) NULL, 
  in_cable_franchise_area varchar(1) NULL, 
  cable_postcode varchar(1) NULL, 
  broadband_tech_available NUMERIC NULL, 
  nga_tech_offered_by_bt varchar(9) NULL, 
  nga_activation_date varchar(16) NULL, 
  alt_net_supplier_code NUMERIC NULL, 
  alt_net_supplier_name NUMERIC NULL, 
  alt_net_tech_supplied NUMERIC NULL, 
  CityFibre postcode passed varchar(1) NULL, 
  Source_of_cable_postcode_flag NUMERIC NULL, 
  Virgin_rFog NUMERIC NULL, 
  Virgin_gig1 NUMERIC NULL, 
  VM_activation_QUARTER NUMERIC NULL, 
  VM_activation_YEAR NUMERIC NULL, 
  multiple_networks_code NUMERIC NULL, 
  altnet_deployment_date NUMERIC NULL, 
  max_nga_speed NUMERIC NULL
);